In [ ]:
import pandas as pd

# Load the CSV data into DataFrames
movies_df = pd.read_csv('movies.csv')
movies2_df = pd.read_csv('movies2.csv')
!pip install pandasql
from pandasql import sqldf

# Define the Pandas SQL function
pysqldf = lambda q: sqldf(q, globals())

# Query 1: Display all the details of movies created by directors Christopher and Matt Reeves.
query1 = """
SELECT *
FROM movies_df
WHERE DirectorName IN ('Christopher', 'Matt Reeves')
"""

result1 = pysqldf(query1)

# Query 2: Display all the details of movies with a duration of 140 minutes to 190 minutes.
query2 = """
SELECT *
FROM movies_df
WHERE Duration BETWEEN 140 AND 190
"""

result2 = pysqldf(query2)

# Query 3: Display all details of movies with ratings above 7 in ascending order.
query3 = """
SELECT *
FROM movies_df
WHERE Ratings > 7
ORDER BY Ratings ASC
"""

result3 = pysqldf(query3)

# Query 4: Display all movie names in descending order.
query4 = """
SELECT MovieName
FROM movies_df
ORDER BY MovieName DESC
"""

result4 = pysqldf(query4)

# Query 5: Display movie names starting with 'P' and their rating is greater than 7.
query5 = """
SELECT MovieName
FROM movies_df
WHERE MovieName LIKE 'P%' AND Ratings > 7
"""

result5 = pysqldf(query5)

# Query 6: Display all movie names with star Arnold Schwarzenegger in ascending order.
query6 = """
SELECT MovieName
FROM movies2_df
WHERE Stars = 'Arnold Schwarzenegger'
ORDER BY MovieName ASC
"""

result6 = pysqldf(query6)

# Query 7: Display all details of the movie with the highest number of votes.
query7 = """
SELECT *
FROM movies2_df
WHERE Votes = (SELECT MAX(Votes) FROM movies2_df)
"""

result7 = pysqldf(query7)

# Query 8: Display movie names with gross collections in descending order.
query8 = """
SELECT MovieName
FROM movies2_df
ORDER BY GrossCollection DESC
"""

result8 = pysqldf(query8)

# Query 9: Display the gross collection of movies with the star Arnold.
query9 = """
SELECT MovieName, GrossCollection
FROM movies2_df
WHERE Stars LIKE '%Arnold%'
"""

result9 = pysqldf(query9)

# Query 10: Display all details of movies with comedy and action genres.
query10 = """
SELECT *
FROM movies2_df
WHERE Genre IN ('Comedy', 'Action')
"""

result10 = pysqldf(query10)

# ...
# Execute the rest of the queries as mentioned in the previous response